name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36

  build:
    name: Tests
    runs-on: ubuntu-latest
    steps: 
      - 
        id: go
        name: "Set up Go 1.x"
        uses: actions/setup-go@v2
        with: 
          go-version: ^1.13
      - 
        name: "Check out code into the Go module directory"
        uses: actions/checkout@v2
      - 
        name: "Run Unit tests"
        run: "go test -race -covermode atomic -coverprofile=covprofile ./...\n"
      - 
        env: 
          GO111MODULE: false
        name: "Install goveralls"
        run: "go get github.com/mattn/goveralls"
      - 
        env: 
          COVERALLS_TOKEN: "${{ secrets.github_token }}"
        name: "Send coverage"
        run: "goveralls -coverprofile=covprofile -service=github"
